config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get :search, controller: :home
  get :searchPost, controller: :home
  root to: 'home#home'  
  resources :regions
  resources :cities
  resources :attractions
  resources :posts do
  	resources :comments
  end
  resources :itineraries do 
    resources :dailies
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users
  devise_for :users, path: '/account', path_names: { sign_in: 'login', sign_out: 'logout'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/city.rb
class City < ApplicationRecord
	has_many :attractions
	has_many :posts
	belongs_to :region
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
    @regions = Region.all
    @attractions = Attraction.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
    @regions = Region.all
    @attractions = Attraction.all
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @cities = City.all
    @regions = Region.all
    @attractions = Attraction.all
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
      @cities = City.all
      @regions = Region.all
      @attractions = Attraction.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :localName, :intro, :content, :region_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper

  def region_pairs
  	#region_names = []
  	@regions.map do |region|
  		[region.name.to_s, region.id.to_i]
  		# region_names += [region.name.to_s, region.id]
    end
	#return region_names
  end

  def region_select (rid)
  	@regions.map do |region|
  		if region.id == rid
  			return region.name.to_s
  		end
    end
  end  

end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :localName %>
    <%= form.text_field :localName %>
  </div>

  <div class="form-group">
  <%= form.label :region_id %>
  <%= form.select :region_id, options_for_select(region_pairs) %>
  </div>

  <div class="form-group">
  <%= form.label :intro %>
  <%= form.text_area  :intro, autofocus: true, autocomplete: "Intro", 
  class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :content %>
    <%= form.cktext_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<br>
  <tbody>
    <% @cities.each do |city| %>
      <div class="card bg-light mt-3">
      <div class="card-body">
        <h3 class="card-title"><strong> <%= link_to city.name, city %> </strong></h3>
        <p class="card-text">
          <span class="postpreview">
          <%= truncate(Sanitize.fragment(city.intro), length: 100) %>
          </span>
        </p>

        <ul class="list-inline text-muted mt-2">
          <li class="list-inline-item">
           <span><%= city.localName %></span>
          </li>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
           <span><%= region_select (city.region_id) %></span>
          </li>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
           <span><%= link_to 'Show', city %></span>
          </li>
          <% if user_signed_in? %>
          <% if current_user.superadmin_role? %>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
            <span><%= link_to 'Edit', edit_city_path(city) %></span>
          </li>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
            <span><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          </li>
          <% end -%>
          <% end -%>
        </ul>
      </div>
      </div>
    <% end %>
  </tbody>

<br><br>
<% if user_signed_in? %>
<% if current_user.superadmin_role? %>
<p> <%= link_to "New City", new_city_path, class: 'btn btn-primary active' %> </p>
<% end -%>
<% end -%>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="card-title"><strong> <%= @city.name %> </strong></h1>
<ul class="list-inline text-muted mt-2">
    <li class="list-inline-item">
        <span><%= region_select (@city.region_id) %></span>
    </li>
    <li class="list-inline-item">|</li>
    <li class="list-inline-item">
        <span>City Name: <%= @city.name %></span>
    </li>
    <li class="list-inline-item">|</li>
    <li class="list-inline-item">
        <span>Local Name: <%= @city.localName %></span>
    </li>
    <li class="list-inline-item">|</li>
    <li class="list-inline-item">
        <span>Comments</span>
    </li>
</ul>

<div class="field">
  <%= @city.content.html_safe %>
</div>



<h1>Attractions in <%= @city.name %></h1>

<table>
  <thead>
    <tr>
      <th>Name    |</th>
      <th>Local Name    |</th>
      <th>Intro    |</th>

      <th>Region/Country    |</th>
      <th>City    |</th>     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each do |attraction| %>
    <% if @city.id == attraction.city_id %>
      <tr>
        <td><%= attraction.name %></td>
        <td><%= attraction.localName %></td>
        <td><%# attraction.content %></td>
        <td><%= attraction.intro %></td>
        <td><%= region_select (attraction.region_id) %></td>
        <td><%= city_select (attraction.city_id) %></td>
        <td><%= link_to 'Show', attraction %></td>
        <% if user_signed_in? %>
        <% if current_user.superadmin_role? %>
        <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
        <td><%= link_to 'Destroy', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
        <% end -%>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <% if current_user.superadmin_role? %>
    <%= link_to 'New Attraction', new_attraction_path %>
  <% end %>
<% end %>