config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get :search, controller: :home
  get :searchPost, controller: :home
  root to: 'home#home'  
  resources :regions
  resources :cities
  resources :attractions
  resources :posts do
  	resources :comments
  end
  resources :itineraries do 
    resources :dailies
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users
  devise_for :users, path: '/account', path_names: { sign_in: 'login', sign_out: 'logout'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/daily.rb
class Daily < ApplicationRecord
	belongs_to :itinerary
	belongs_to :user
	#belongs_to :attraction
	#belongs_to :city
	#belongs_to :region
	#belongs_to :post

	#def post_title
	#	post.try(:title)
	#end

	#def post_title=(title)
	#	self.post = Post.find_by_title(title) if title.present?
	#end	

end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
	before_action :set_daily, only: [:show, :edit, :update, :destroy]
  before_action :force_json, only: :search

 def index
    @cities = City.all
    @regions = Region.all
    @attractions = Attraction.all
    @posts = Post.all
  end
  def show
    @cities = City.all
    @regions = Region.all
    @attractions = Attraction.all
    @posts = Post.all
  end
  def update
  end
  # POST /dailies
  # POST /dailies.json
  def create
    @itinerary = Itinerary.find(params[:itinerary_id])
    @daily = @itinerary.dailies.create(params[:daily].permit(:daynumber, :dailydate, :region_id, :city_id, :attraction_id, :user_id, :post_id, :content))
    redirect_to itinerary_path(@itinerary)
    @cities = City.all
    @regions = Region.all
    @attractions = Attraction.all
    @posts = Post.all
  end

  def new
    @cities = City.all
    @regions = Region.all
    @attractions = Attraction.all
    @posts = Post.all
  end

  def destroy
  	@itinerary = Itinerary.find(params[:itinerary_id])
  	@daily = @itinerary.dailies.find(params[:id])
	 @daily.destroy
    redirect_to itinerary_path(@itinerary)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily
      @cities = City.all
      @regions = Region.all
      @attractions = Attraction.all
      @posts = Post.all
      # @daily = @itinerary.dailies.find(params[:id])
    end

end

app/helpers/dailies_helper.rb
module DailiesHelper

  def region_pairs
  	@regions.map do |region|
  		[region.name.to_s, region.id.to_i]
    end
  end

  def city_pairs
  	@cities.map do |city|
   		[city.name.to_s, city.id.to_i]
    end
  end

  def attraction_pairs
  	@attractions.map do |attraction|
   		[attraction.name.to_s, attraction.id.to_i]
    end
  end

  def post_pairs
    @posts.map do |post|
      [post.title.to_s, post.id.to_i]
    end
  end


  def region_select (rid)
  	@regions.map do |region|
  		if region.id == rid
  			return region.name.to_s
  		end
    end
  end
    
  def city_select (cid)
  	@cities.map do |city|
  		if city.id == cid
  			return city.name.to_s
  		end
    end
  end 

  def attraction_select (aid)
  	@attractions.map do |attraction|
  		if attraction.id == aid
  			return attraction.name.to_s
  		end
    end
  end

  def post_select (pid)
    @posts.map do |post|
      if post.id == pid
        return post.title.to_s
      end
    end
  end

  def region_link_select (rid)
    @regions.map do |region|
      if region.id == rid
        return region_path(region)
      end
    end
  end

  def city_link_select (cid)
    @cities.map do |city|
      if city.id == cid
        return city_path(city)
      end
    end
  end

  def attraction_link_select (aid)
    @attractions.map do |attraction|
      if attraction.id == aid
        return attraction_path(attraction)
      end
    end
  end

  def post_link_select (pid)
    @posts.map do |post|
      if post.id == pid
        return post_path(post)
      end
    end
  end

end

app/views/dailies/_daily.html.erb
<p>
	<li>Day: <%= daily.daynumber %> | Date: <%= daily.dailydate.try(:strftime, '%v') %> </li>
	<% if daily.region_id != nil %>
		<span>Country: <%= link_to region_select(daily.region_id), region_link_select(daily.region_id) %></span>
	<% end %>
	<% if daily.city_id != nil %>
		<span> | City: <%= link_to city_select(daily.city_id), city_link_select(daily.city_id) %></span>
	<% end %>
	<% if daily.attraction_id != nil %>
		<span> | Attraction: <%= link_to attraction_select(daily.attraction_id), attraction_link_select(daily.attraction_id) %></span>
	<% end %>
</p>
<p>
	<% if daily.post_id != nil %>
		<span>Article: <%= link_to post_select(daily.post_id), post_link_select(daily.post_id) %></span>
	<% end %>
</p>
<p>
<%# time_ago_in_words(daily.created_at) %>
	<% if daily.content != '' %>
		Content: <%= daily.content %>
	<% end %>
</p>

<% if user_signed_in? %>
	<% if @current_user.id == daily.user_id %>
	<p><%= link_to 'Delete',[daily.itinerary,daily], method: :delete, data: { confirm: 'Are you sure?' } %></p>
	<% end %>
<% end %>

app/views/dailies/_form.html.erb
<%= form_for([@itinerary, @itinerary.dailies.build]) do |form| %>

  <p>
    <%= form.label 'Day Number' %><br>
    <%= form.number_field :daynumber %>
  </p>

  <p>
    <%= form.label 'Select Date' %><br>
    <%= form.date_select :dailydate %>
  </p>

  <p>
  <%= form.label :region_id %>
  <%= form.collection_select :region_id, Region.order(:name), :id, :name, include_blank: true %>
  </p>

  <p>
  <%= form.label :city_id %>
  <%= form.grouped_collection_select :city_id, Region.order(:name), :cities, :name, :id, :name, include_blank: true %>
  </p>

  <p>
  <%= form.label :attraction_id %>
  <%= form.grouped_collection_select :attraction_id, City.order(:name), :attractions, :name, :id, :name, include_blank: true %>
  </p>

  <p><%= "Cannot Find the Attraction You Need?" %>&ensp;<%= link_to "Create New Attraction",  new_attraction_path, class: 'text-primary' %></p>

  <p>
    <%= form.label 'Article' %>
    <%= text_field_tag(:post_id, nil, id:"post_name", data: { behavior: 'autocompletepost' }, placeholder: (t('posts.show.title')), class: 'form-control mr-sm-3') %>
  </p>  

  <p>
    <%= form.label :content %>
    <%= form.cktext_area :content %>
  </p>

  <%= form.hidden_field :post_id, id: "post_id" %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/dailies/edit.html.erb
<h1>Editing Daily</h1>

<%= render 'form', daily: @daily %>

<%= link_to 'Show', @daily %> |
<%= link_to 'Back', dailies_path %>

app/views/dailies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dailies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Localname</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dailies.each do |daily| %>
      <tr>
        <td><%= daily.name %></td>
        <td><%= daily.localName %></td>
        <td><%= daily.content %></td>
        <td><%= link_to 'Show', daily %></td>
        <td><%= link_to 'Edit', edit_daily_path(daily) %></td>
        <td><%= link_to 'Destroy', daily, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily', new_daily_path %>

app/views/dailies/new.html.erb
<h1>New Daily</h1>

<%= render 'form', daily: @daily %>

<%= link_to 'Back', dailies_path %>

app/views/dailies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @daily.name %>
</p>

<p>
  <strong>Localname:</strong>
  <%= @daily.localName %>
</p>

<p>
  <strong>Content:</strong>
  <%= @daily.content %>
</p>

<%= link_to 'Edit', edit_daily_path(@daily) %> |
<%= link_to 'Back', dailies_path %>