config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get :search, controller: :home
  get :searchPost, controller: :home
  root to: 'home#home'  
  resources :regions
  resources :cities
  resources :attractions
  resources :posts do
  	resources :comments
  end
  resources :itineraries do 
    resources :dailies
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users
  devise_for :users, path: '/account', path_names: { sign_in: 'login', sign_out: 'logout'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/region.rb
class Region < ApplicationRecord
	has_many :cities
	has_many :attractions
	has_many :posts
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
    @cities = City.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @cities = City.all
    @regions = Region.all
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @cities = City.all
    @regions = Region.all
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @cities = City.all
      @regions = Region.all
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name, :localName, :content, :intro)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_with(model: region, local: true) do |form| %>
  <% if region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :localName %>
    <%= form.text_field :localName %>
  </div>

  <div class="form-group">
  <%= form.label :intro %>
  <%= form.text_area  :intro, autofocus: true, autocomplete: "Intro", 
  class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :content %>
    <%= form.cktext_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Regions</h1>

<br>
  <tbody>
    <% @regions.each do |region| %>
      <div class="card bg-light mt-3">
      <div class="card-body">
        <h3 class="card-title"><strong> <%= link_to region.name, region %> </strong></h3>
        <p class="card-text">
          <span class="postpreview">
          <%= truncate(Sanitize.fragment(region.intro), length: 100) %>
          </span>
        </p>

        <ul class="list-inline text-muted mt-2">
          <li class="list-inline-item">
           <span><%= region.localName %></span>
          </li>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
           <span><%= link_to 'Show', region %></span>
          </li>
          <% if user_signed_in? %>
          <% if current_user.superadmin_role? %>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
            <span><%= link_to 'Edit', edit_region_path(region) %></span>
          </li>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
            <span><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          </li>
          <% end -%>
          <% end -%>
        </ul>
      </div>
      </div>
    <% end %>
  </tbody>

<br><br>
<% if user_signed_in? %>
<% if current_user.superadmin_role? %>
<p> <%= link_to "New Region", new_region_path, class: 'btn btn-primary active' %> </p>
<% end -%>
<% end -%>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="card-title"><strong> <%= @region.name %> </strong></h1>
<ul class="list-inline text-muted mt-2">
    <li class="list-inline-item">
        <span>Region Name: <%= @region.name %></span>
    </li>
    <li class="list-inline-item">|</li>
    <li class="list-inline-item">
        <span>Local Name: <%= @region.localName %></span>
    </li>
    <li class="list-inline-item">|</li>
    <li class="list-inline-item">
        <span>Comments</span>
    </li>
</ul>

<div class="field">
  <%= @region.content.html_safe %>
</div>



<h1>Cities in <%= @region.name %></h1>
<table>
  <thead>
    <tr>
      <th>Name    |</th>
      <th>Local Name    |</th>
      <th>Intro    |</th>

      <th>Region/Country    |</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
    <% if @region.id == city.region_id %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.localName %></td>
        <td><%= city.intro %></td>
        <td><%# city.content %></td>
        <td><%= region_select (city.region_id) %></td>
        <td><%= link_to 'Show', city %></td>
        <% if user_signed_in? %>
        <% if current_user.superadmin_role? %>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
        <% end -%>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
	<% if current_user.superadmin_role? %>
		<%= link_to 'New City', new_city_path %>
	<% end %>
<% end %>