config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get :search, controller: :home
  get :searchPost, controller: :home
  root to: 'home#home'  
  resources :regions
  resources :cities
  resources :attractions
  resources :posts do
  	resources :comments
  end
  resources :itineraries do 
    resources :dailies
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users
  devise_for :users, path: '/account', path_names: { sign_in: 'login', sign_out: 'logout'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]

  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all
    @cities = City.all
    @regions = Region.all
    @posts = Post.all
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
    @attractions = Attraction.all
    @regions = Region.all
    @cities = City.all
    @posts = Post.all
  end

  # GET /attractions/1/edit
  def edit
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attractions = Attraction.all
    @regions = Region.all
    @cities = City.all
    @posts = Post.all
    @attraction = Attraction.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attractions = Attraction.all
      @regions = Region.all
      @cities = City.all
      @posts = Post.all
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:name, :localName, :content, :intro, :region_id, :city_id)
    end
end

app/helpers/attractions_helper.rb
module AttractionsHelper

  def region_pairs
  	@regions.map do |region|
  		[region.name.to_s, region.id.to_i]
    end
  end

  def city_pairs
  	@cities.map do |city|
   			[city.name.to_s, city.id.to_i]
    end
  end

  def region_select (rid)
  	@regions.map do |region|
  		if region.id == rid
  			return region.name.to_s
  		end
    end
  end
    
  def city_select (cid)
  	@cities.map do |city|
  		if city.id == cid
  			return city.name.to_s
  		end
    end
  end 

end

app/views/attractions/_form.html.erb
<%= form_with(model: attraction, local: true) do |form| %>
  <% if attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :localName %>
    <%= form.text_field :localName %>
  </div>

  <div class="form-group">
  <%= form.label :region_id %>
  <%= form.collection_select :region_id, Region.order(:name), :id, :name, include_blank: true %>
  </div>

  <div class="form-group">
  <%= form.label :city_id %>
  <%= form.grouped_collection_select :city_id, Region.order(:name), :cities, :name, :id, :name, include_blank: true %>
  </div>


  <div class="form-group">
  <%= form.label :intro %>
  <%= form.text_area  :intro, autofocus: true, autocomplete: "Intro", 
  class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :content %>
    <%= form.cktext_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attractions</h1>

<br>
  <tbody>
    <% @attractions.each do |attraction| %>
      <div class="card bg-light mt-3">
      <div class="card-body">
        <h3 class="card-title"><strong> <%= link_to attraction.name, attraction %> </strong></h3>
        <p class="card-text">
          <span class="postpreview">
          <%= truncate(Sanitize.fragment(attraction.intro), length: 100) %>
          </span>
        </p>

        <ul class="list-inline text-muted mt-2">
          <li class="list-inline-item">
           <span><%= attraction.localName %></span>
          </li>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
           <span><%= city_select(attraction.city_id) %></span>
          </li>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
           <span><%= region_select(attraction.region_id) %></span>
          </li>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
           <span><%= link_to 'Show', attraction %></span>
          </li>
          <% if user_signed_in? %>
          <% if current_user.superadmin_role? %>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
            <span><%= link_to 'Edit', edit_attraction_path(attraction) %></span>
          </li>
          <li class="list-inline-item">|</li>
          <li class="list-inline-item">
            <span><%= link_to 'Destroy', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          </li>
          <% end -%>
          <% end -%>
        </ul>
      </div>
      </div>
    <% end %>
  </tbody>

<br><br>
<% if user_signed_in? %>
<p> <%= link_to "New Attraction", new_attraction_path, class: 'btn btn-primary active' %> </p>
<% end -%>

app/views/attractions/new.html.erb
<h1>New Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Back', attractions_path %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="card-title"><strong> <%= @attraction.name %> </strong></h1>
<ul class="list-inline text-muted mt-2">
    <li class="list-inline-item">
        <span><%= region_select (@attraction.region_id) %></span>
    </li>
    <li class="list-inline-item">|</li>
    <li class="list-inline-item">
        <span><%= city_select (@attraction.city_id) %></span>
    </li>
    <li class="list-inline-item">|</li>
    <li class="list-inline-item">
        <span>Attraction Name: <%= @attraction.name %></span>
    </li>
    <li class="list-inline-item">|</li>
    <li class="list-inline-item">
        <span>Local Name: <%= @attraction.localName %></span>
    </li>
    <li class="list-inline-item">|</li>
    <li class="list-inline-item">
        <span>Comments</span>
    </li>
</ul>

<div class="field">
  <%= @attraction.content.html_safe %>
</div>


<h1>Articles in <%= @attraction.name %></h1>

<table>
  <thead>
    <tr>
      <th>Title    |</th>
      <th>Region/Country    |</th>
      <th>City    |</th>     
      <th>Attraction    |</th>
      <th>Views    |</th>     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
    <% if @attraction.id == post.attraction_id %>
      <tr>
        <td><%= post.title %></td>
        <td><%= region_select (post.region_id) %></td>
        <td><%= city_select (post.city_id) %></td>
        <td><%= attraction_select (post.attraction_id) %></td>
        <td><%= post.view %></td>
        <td><%= link_to 'Show', post %></td>
        <% if user_signed_in? %>
        <% if current_user.superadmin_role? %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
        <% end -%>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <% if current_user.superadmin_role? %>
    <%= link_to 'New Article', new_post_path %>
  <% end %>
<% end %>